version: '3.8'
services:
  MYSQL:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sidaoui
      MYSQL_DATABASE: skier
      MYSQL_USER: sidaoui
      MYSQL_PASSWORD: skier
    ports:
      - "3306:3306"
     

  gestion-station-ski-front:
    image: sidaouimohamedamine/gestion-station-ski-front:latest
    ports:
      - "4200:4200"
    environment:
      BASE_URL: http://gestion-station-ski-backend:8089
    depends_on:
      - gestion-station-ski-backend

  gestion-station-ski-backend:
    image: sidaouimohamedamine/gestion-station-ski:latest
    ports:
      - "8089:8089"
    depends_on:
      - MYSQL
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/skier?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: sidaoui
      SPRING_DATASOURCE_PASSWORD: skier
      SPRING_SERVER_PORT: 8089